export const demoRiders = [
      {
        riderNumber: "101",
        firstName: "Sam",
        lastName: "Hill",
        caLicenceNumber: "A011249",
        category: "Elite",
        status: "WAITING",
        startTime: null,
        finishTime: null,
        totalTime: null,
      },
      {
        riderNumber: "102",
        name: "Greg Minnaar",
        firstName: "Greg",
        lastName: "Minaar",
        caLicenceNumber: "Ac615589",
        category: "Elite",
        status: "WAITING",
        startTime: null,
        finishTime: null,
        totalTime: null,
      },
      {
        riderNumber: "103",
        firstName: "Rachel",
        lastName: "Atherton",
        caLicenceNumber: "Ac912589",
        category: "Elite",
        status: "WAITING",
        startTime: null,
        finishTime: null,
        totalTime: null,
      },
      {
        riderNumber: "201",
        firstName: "Clem",
        lastName: "Fandango",
        caLicenceNumber: "Ac917589",
        category: "Junior",
        status: "WAITING",
        startTime: null,
        finishTime: null,
        totalTime: null,
      },
    ];